/*
 * generated by Xtext
 */
package org.ui.contentassist

import org.ui.contentassist.AbstractAtsLangProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class AtsLangProposalProvider extends AbstractAtsLangProposalProvider {
}
