/*
 * generated by Xtext
 */
package org.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AtsLangUiModule extends org.ui.AbstractAtsLangUiModule {
	public AtsLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
