/*
 * generated by Xtext
 */
package org;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AtsLangStandaloneSetup extends AtsLangStandaloneSetupGenerated{

	public static void doSetup() {
		new AtsLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

